In [133]:
import os
import numpy as np
import gc
import load_data as ld


ImportError: No module named load_data

In [130]:
subjects = ["/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_04799/",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_04820",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_04847",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_05680",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject-05710"]

trials_data = []
info = []
meta = []
for subject in subjects:
    info_files, trial_data, meta_files = ld.get_raw_data(subject, len(trials_data))
    trials_data.extend(trial_data)
    info.extend(info_files)
    meta.extend(meta_files)
    os.chdir(cwd)


NameError: name 'ld' is not defined

In [71]:
def load_data(data_dir):
    print("Loading data for: ", data_dir.split('/')[2])

    os.chdir(data_dir)
    cwd = os.getcwd()

    trials = []
    info_files = []

    for path, sub_dirs, files in os.walk(cwd):
        for name in sub_dirs:
            cwd = os.path.join(path, name)
            trial_data = open(cwd + "/data.csv").read()
            # get data by lines but drop last line as it is empty
            trial_data = trial_data.split("\n")[:-1]
            trial_data = np.array([i.split(",") for i in trial_data])
            # trial_data.append(open(cwd + "\\info.data").read())
            trials.append(trial_data)

            info = {}
            with open(cwd + "/info.data") as f:
                for line in f:
                    (key, val) = line.rstrip('\n').split(':')
                    info[key] = val

            info['trial'] = len(trials) - 1
            info_files.append(info)

    print("Done!")
    return info_files, trials  # , meta

In [72]:
def get_related_trials(info, trials):
#     print(info)
    # print('Inside GRT')
    result = []
    for item in info:
        i = int(item['trial'])
        result.append(trials[i])
    # print("Done GRT!")
    return result


In [73]:
cwd = os.getcwd()

In [74]:
subjects = ["/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_04799/",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_04820",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_04847",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject_05680",
                "/Users/satrajitmaitra/fmri/Data/ExtractedData/Subject-05710"]

trials_data = []
info = []
for subject in subjects:
    info_files, trial_data = load_data(subject)
    trials_data.extend(trial_data)
    info.extend(info_files)
    os.chdir(cwd)

pic_info = [d for d in info if (d['firstStimulus'] == 'P' and int(d['cond']) > 1)]
sen_info = [d for d in info if (d['firstStimulus'] == 'S' and int(d['cond']) > 1)]
#     print(pic_info)
pic_data = get_related_trials(pic_info, trials_data)
sen_data = get_related_trials(sen_info, trials_data)

('Loading data for: ', 'satrajitmaitra')
Done!
('Loading data for: ', 'satrajitmaitra')
Done!
('Loading data for: ', 'satrajitmaitra')
Done!
('Loading data for: ', 'satrajitmaitra')
Done!
('Loading data for: ', 'satrajitmaitra')
Done!


In [75]:
trim_pic = []
for item in pic_data:
    trim_pic.append(np.concatenate((item[:][1:16], item[:][17:32])))

In [76]:
trim_sen = []
for item in sen_data:
    trim_sen.append(np.concatenate((item[:][1:16], item[:][17:32])))

In [86]:
final_trim_pic = (np.array(trim_pic)).reshape(100 * 30, 4949)
final_trim_sen = (np.array(trim_sen)).reshape(100 * 30, 4949)

In [87]:
final_trim_pic

array([['-10.593797240342113', '0.8026951383106592',
        '-1.4955773899098275', ..., '2.1126169844402165',
        '6.986682070448923', '11.756857905334046'],
       ['-1.5349219289358769', '-2.4042781361703063',
        '-1.0175223961505446', ..., '4.365480446026905',
        '10.328206230926016', '9.062457323978325'],
       ['5.296764194669665', '-0.6524399242436287', '0.4032080549590386',
        ..., '0.37057875115230465', '5.232179573225737',
        '8.651411925672228'],
       ...,
       ['-9.970476396041672', '-1.6465127638486912',
        '0.9572064835240788', ..., '6.293089122735588',
        '16.108545167101333', '22.32632017411432'],
       ['-1.340432445057977', '-3.9501829309961223',
        '-0.24139729872833357', ..., '2.4981403213910967',
        '8.4298042173011', '13.357054147311523'],
       ['-0.03338605317975411', '1.7711846136756393',
        '1.2223887733036283', ..., '1.1454772950443721',
        '12.376107945484108', '21.08343618390667']], dtype='|S23')

In [92]:
print(final_trim_pic.shape)

(3000, 4949)


In [93]:
mean_value = np.mean(final_trim_pic.astype(np.float))
array2 = np.full((3000, 4949), mean_value)
final_trim_pic = np.subtract(final_trim_pic.astype(np.float), array2)

In [94]:
mean_value

0.23172304838522073

In [95]:
array2

array([[0.23172305, 0.23172305, 0.23172305, ..., 0.23172305, 0.23172305,
        0.23172305],
       [0.23172305, 0.23172305, 0.23172305, ..., 0.23172305, 0.23172305,
        0.23172305],
       [0.23172305, 0.23172305, 0.23172305, ..., 0.23172305, 0.23172305,
        0.23172305],
       ...,
       [0.23172305, 0.23172305, 0.23172305, ..., 0.23172305, 0.23172305,
        0.23172305],
       [0.23172305, 0.23172305, 0.23172305, ..., 0.23172305, 0.23172305,
        0.23172305],
       [0.23172305, 0.23172305, 0.23172305, ..., 0.23172305, 0.23172305,
        0.23172305]])

In [96]:
final_trim_pic

array([[-10.82552029,   0.57097209,  -1.72730044, ...,   1.88089394,
          6.75495902,  11.52513486],
       [ -1.76664498,  -2.63600118,  -1.24924544, ...,   4.1337574 ,
         10.09648318,   8.83073428],
       [  5.06504115,  -0.88416297,   0.17148501, ...,   0.1388557 ,
          5.00045652,   8.41968888],
       ...,
       [-10.20219944,  -1.87823581,   0.72548344, ...,   6.06136607,
         15.87682212,  22.09459713],
       [ -1.57215549,  -4.18190598,  -0.47312035, ...,   2.26641727,
          8.19808117,  13.1253311 ],
       [ -0.2651091 ,   1.53946157,   0.99066572, ...,   0.91375425,
         12.1443849 ,  20.85171314]])

In [97]:
sigma = np.cov(final_trim_pic.T)

In [99]:
sigma.shape

(4949, 4949)

In [100]:
eigVals, eigVec = np.linalg.eig(sigma)

In [104]:
eigVals

array([ 1.42932170e+03+0.00000000e+00j,  1.08834946e+03+0.00000000e+00j,
        9.04212999e+02+0.00000000e+00j, ...,
       -1.82385547e-17-4.62067658e-17j,  1.53637495e-16+1.13327769e-16j,
        1.53637495e-16-1.13327769e-16j])

In [125]:
eigVec

array([[ 3.37438710e-02+0.j        , -5.79574350e-02+0.j        ,
        -5.38386478e-03+0.j        , ...,  5.94696105e-03-0.00116148j,
         5.94696105e-03+0.00116148j, -3.56498850e-05+0.j        ],
       [ 1.68409806e-02+0.j        ,  1.63977587e-02+0.j        ,
         2.73323854e-02+0.j        , ...,  1.04548798e-02-0.00410308j,
         1.04548798e-02+0.00410308j, -1.16775333e-02+0.j        ],
       [ 1.17172812e-02+0.j        ,  1.69861747e-02+0.j        ,
        -1.32839223e-03+0.j        , ...,  1.88838013e-02-0.00018294j,
         1.88838013e-02+0.00018294j,  1.20650016e-03+0.j        ],
       ...,
       [ 3.48708207e-02+0.j        , -1.24383689e-02+0.j        ,
         9.53842949e-03+0.j        , ..., -1.85034902e-02-0.00165119j,
        -1.85034902e-02+0.00165119j, -1.60350730e-02+0.j        ],
       [ 1.05686034e-01+0.j        ,  2.59832527e-03+0.j        ,
         3.25159443e-02+0.j        , ...,  2.29508231e-02-0.03753634j,
         2.29508231e-02+0.03753634j

In [110]:
sorted_index = eigVals.argsort()[::-1]

In [126]:
eigVals = eigVals[sorted_index]
eigVec = eigVec[:,sorted_index]

In [127]:
eigVals

array([1.42932170e+03+0.00000000e+00j, 1.08834946e+03+0.00000000e+00j,
       9.04212999e+02+0.00000000e+00j, ...,
       6.17785520e-14+2.77390640e-15j, 6.17785520e-14-2.77390640e-15j,
       6.07478496e-14+6.43517793e-14j])

In [129]:
eigVec.shape

(4949, 4949)